name = "cgv-alert-trigger"
main = "worker.js"
compatibility_date = "2026-09-18"
keep_vars = true

[vars]
DISCORD_APPLICATION_ID = "1550913485511069757"

[[d1_databases]]
binding = "DB"
database_name = "cgv-alert-status"
database_id = "da21f615-7792-4a57-a612-890198e606f0"

[triggers]
crons = ["*/5 * * * *"]
